# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Updating kohaku on server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Updating Kohaku
      uses: appleboy/ssh-action@master
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}
      with:
        host: ${{ secrets.PRIVATE_HOST }}
        username: ${{ secrets.PRIVATE_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PRIVATE_PORT }}
        envs: WEBHOOK
        script: sh update_kohaku.sh
        
